[package]
name = "metadata_relay_p2p"
version = "0.1.0"
edition = "2021"

[lib]
name = "metadata_relay_p2p"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.34.0"
mydia_p2p_core = { path = "../../../native/mydia_p2p_core" }
tokio = { version = "1.43", features = ["full"] }
