apiVersion: v1
kind: Service
metadata:
  name: metadata-relay
  namespace: metadata-relay
  labels:
    app.kubernetes.io/name: metadata-relay
    app.kubernetes.io/component: relay-service
spec:
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: metadata-relay
    app.kubernetes.io/component: relay-service
