apiVersion: v1
kind: ConfigMap
metadata:
  name: iroh-relay-config
  namespace: iroh-relay
data:
  config.toml: |
    enable_relay = true
    enable_quic_addr_discovery = true

    http_bind_addr = "0.0.0.0:80"
    https_bind_addr = "0.0.0.0:443"
    quic_bind_addr = "0.0.0.0:7842"

    metrics_addr = "0.0.0.0:9090"

    [tls]
    cert_mode = "Manual"
    manual_cert_path = "/certs/tls.crt"
    manual_key_path = "/certs/tls.key"

    hostname = "cae1-1.relay.mydia.dev"
