apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: iroh-relay

resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - dns.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: mydia
    includeSelectors: true
