apiVersion: v1
kind: Service
metadata:
  name: iroh-relay
  namespace: iroh-relay
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      name: http
    - port: 443
      targetPort: https
      name: https
    - port: 7842
      targetPort: quic
      protocol: UDP
      name: quic
    - port: 3478
      targetPort: stun
      protocol: UDP
      name: stun
    - port: 9090
      targetPort: metrics
      name: metrics
  selector:
    app.kubernetes.io/name: iroh-relay
